version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:1.4
    environment:
      - SERVICES=lambda,s3,apigateway,iam
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/var/lib/localstack"
